### ISSUE TITLE
Is there a model size limit?

### ISSUE THREAD

**Issue by flatsiedatsie** [tangledgroup/llama-cpp-wasm#2]
This project looks like what I've been waiting for. But unfortunately the fifrst model I tried to load (in Brave), seemed to get stuck after downloading.

`https://huggingface.co/TheBloke/TowerInstruct-7B-v0.1-GGUF/resolve/main/towerinstruct-7b-v0.1.Q4_K_S.gguf`

I then tried the same on Firefox with WASM set to verbose, and saw:
```
TypeError: Response constructor: ArrayBuffer branch of (Blob or (ArrayBufferView or ArrayBuffer) or FormData or URLSearchParams or ReadableStream or USVString) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
```

Is there a model size limit? If so, is there a way around this?

**Comment by jpohhhh** [comment]
Been using this project heavily and I think so, no 7B model I've tried work at any quant.

I think it's due to WASM memory limits, see ex. memory64 on this page. https://v8.dev/blog/4gb-wasm-memory

I think I picked this up from people doing Stable Diffusion via ONNX on web, but I'm not 100% sure. 

Running llama.cpp in WASM is _very_ fresh so there's not much precedent to rely on, the only other attempt I'm aware of was in May 2023 and didn't get far beyond proof of concept

**Comment by flatsiedatsie** [comment]
From looking at the code my conclusion was that the issue came from using `XMLhttpRequest` to load the models into an`ArrayBuffer`, since those have a 2Gb limit.

[Web-LLM](https://github.com/mlc-ai/web-llm) is able to load bigger models, and they seem to concatenate parts into a bigger blob, and use `fetch` as part of that.

They also support WebGPU... but after two days of trying to get a custom model to work in Web-LLM I stumnled upon this project, and got the model up and running in 5 minutes... 

So for now I'm very happy with this project, despite it's limitations.

**Comment by flatsiedatsie** [comment]
solved by: https://github.com/ngxson/wllama
